"uid"                :    'root'
"pwd"                :    'root'
"browser"            :    'chrome'
"database"           :    'nifty50'
"driver_location"    :    'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
"webdriver_location" :    'C:\Docs\Project\Learning_material\chromedriver\chromedriver.exe'